### PR TITLE
Added and fixed PC speaker sound not working sometimes due to spkrpos not being set, now has high pitch sound with c2 freq

### PR DESCRIPTION
**Pull request by Smart6502**
**Added PCSpkr init function to change spkrpos, so now sound always works**

### CODE REVIEW

**Comment by Smart6502** [comment]
btw there is a small conflict which is insignificant in kernel/main.c you can fix manually its one line :)

**Comment by Smart6502** [comment]
QEMU does give a warning about using `-soundhw` but I found no docs on `-machine pcspk-audiodev`, but it works so its ok for now

**Comment by Smart6502** [comment]
**I beg of thee, not to use earphones or rip ears**

**Comment by Abb1x** [comment]
nice :)

**Comment by Smart6502** [comment]
Thanks!!

**Pull request merged**
