### PR TITLE
PCI multifunction devices parsing

### PR DESCRIPTION
**Pull request by Smart6502**
**You asked for it**

*So I did it :)*
You can double check using QEMU compatmonitor

### CODE REVIEW

**Comment by Smart6502** [comment]
*You should merge the PC Speaker pull request before this one*

**Comment by Abb1x** [comment]
> Also you mention in your README that AHCI/SATA would be nice so I added the QEMU option for that, tell me here if I should do that.

SATA requires virtual memory, so no.

**Comment by Smart6502** [comment]
> Also, please format your code.

Wdym

**Comment by Smart6502** [comment]
> > Also you mention in your README that AHCI/SATA would be nice so I added the QEMU option for that, tell me here if I should do that.
> 
> SATA requires virtual memory, so no.

Ah yes Ill wait for you then!

**Comment by Smart6502** [comment]
> > > Also, please format your code.
> > 
> > Wdym
> 
> Format it so that it follows the formatting we use (e.g: newline before braces, etc.) You can use the script in scripts/development to format it.

I will commit again in sometime after i el the formatting or whatever using the script thingy dont close this also can you talk on discord its weird here

**Comment by Smart6502** [comment]
Ok I did the reformatting

**Pull request closed without merging**
